language: cpp

compiler:
    - clang
    - gcc

install:
  # credit: https://github.com/beark/ftl/
  # install g++ 4.8, if tests are run with g++
  - if [ "`echo $CXX`" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo apt-get update; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  # install libc++ if tests are run with clang++
  - if [ "`echo $CXX`" == "clang++" ]; then cwd=$(pwd); fi
  - if [ "`echo $CXX`" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "`echo $CXX`" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cd libcxx && mkdir build && cd build; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cmake -DLIBCXX_CXX_ABI=libcxxabi -DCLIBCXX_LIBCXXABI_INCLUDE_PATHS="../../libcxxabi/include" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../; fi
  - if [ "`echo $CXX`" == "clang++" ]; then make && sudo make install; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cd ../../; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cd libcxxabi/lib && ./buildit; fi
  - if [ "`echo $CXX`" == "clang++" ]; then sudo cp ./libc++abi.so.1.0 /usr/lib; fi
  - if [ "`echo $CXX`" == "clang++" ]; then sudo ln -sf /usr/lib/libc++abi.so.1.0 /usr/lib/libc++abi.so.1; fi
  - if [ "`echo $CXX`" == "clang++" ]; then sudo ln -sf /usr/lib/libc++abi.so.1 /usr/lib/libc++abi.so; fi

before_script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug

script:
  - make
