notifications:
  irc: "chat.freenode.net#meta-toolkit"

language: cpp

compiler:
    - clang
    - gcc

install:
  # credit: https://github.com/beark/ftl/
  # install g++ 4.8, if tests are run with g++
  - if [ "`echo $CXX`" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo apt-get update; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  # install libc++ if tests are run with clang++
  - if [ "`echo $CXX`" == "clang++" ]; then cwd=$(pwd); fi
  - if [ "`echo $CXX`" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk@181765 libcxx; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cd libcxx/lib && ./buildit; fi
  - if [ "`echo $CXX`" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "`echo $CXX`" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "`echo $CXX`" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "`echo $CXX`" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

before_script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug

script:
  - make
