libsvm-modules = "/home/sean/projects/meta/deps/libsvm-modules/"
prefix = "/home/sean/projects/meta-data/"
stop-words = "/home/sean/projects/meta/data/lemur-stopwords.txt"
function-words = "/home/sean/projects/meta/data/function-words.txt"

#corpus-type = "file-corpus"
#dataset = "imdb"
#list = "imdb"
#forward-index = "imdb-fwd"
#inverted-index = "imdb-inv"

corpus-type = "line-corpus"
dataset = "topics"
list = "topics"
forward-index = "topics-fwd"
inverted-index = "topics-inv"

[[analyzers]]
method = "libsvm"

#[[analyzers]]
#method = "ngram"
#ngramOpt = "Word"
#ngram = 1

#[[analyzers]]
#method = "tree"
#treeOpt = "Subtree"

[lda]
#inference = "gibbs"
#inference = "pargibbs"
inference = "cvb"
max-iters = 1000
alpha = 1.0
beta = 1.0
topics = 4
model-prefix = "lda_model"
