stop-words = "../data/lemur-stopwords.txt"
libsvm-modules = "../deps/libsvm-modules/"
prefix = "../data/"
function-words = "../data/function-words.txt"
punctuation = "../data/sentence-boundaries/sentence-punctuation.txt"
start-exceptions = "../data/sentence-boundaries/sentence-start-exceptions.txt"
end-exceptions = "../data/sentence-boundaries/sentence-end-exceptions.txt"
query-judgements = "../data/ceeaus/qrels.txt"

#corpus-type = "file-corpus"
#dataset = "imdb"
#list = "imdb"
#forward-index = "imdb-fwd"
#inverted-index = "imdb-inv"

corpus-type = "line-corpus"
dataset = "topics"
list = "topics"
forward-index = "topics-fwd"
inverted-index = "topics-inv"

[[analyzers]]
method = "libsvm"

#[[analyzers]]
#method = "ngram-word"
#ngram = 1

#[[analyzers]]
#method = "tree"
#treeOpt = "Subtree"

[lda]
#inference = "gibbs"
#inference = "pargibbs"
inference = "cvb"
max-iters = 1000
alpha = 1.0
beta = 1.0
topics = 4
model-prefix = "lda_model"
